### ISSUE TITLE
Switch over to official go management library

### ISSUE THREAD

**Issue by carlsverre** [singlestore-labs/vapor#4]
https://github.com/singlestore-labs/singlestore-go

**Comment by ricochet** [comment]
Annoying thing: I want to pass in a releaseID which is an intentionally undocumented argument of the API. I don't see an easy way to use PostV0betaClusters with a modified body.

That means the call will need to be my own body buffer, e.g.:
`NewPostV0betaClustersRequestWithBody(server, "application/json", bodyReader)`
